# Generated by Django 2.1.1 on 2018-12-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '认证方式',
                'verbose_name_plural': '认证方式',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '厂商',
                'verbose_name_plural': '厂商',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备名称')),
                ('IP', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('enable', models.BooleanField(default=False, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备',
            },
        ),
        migrations.CreateModel(
            name='Olt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=32)),
                ('interface', models.CharField(max_length=32)),
                ('selent_onus', models.CharField(default='None', max_length=128)),
                ('epon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Onu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=32)),
                ('mac', models.CharField(max_length=32)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Olt')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('authmode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app01.AuthMode')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app01.Company')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '软件版本',
                'verbose_name_plural': '软件版本',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app01.Version'),
        ),
        migrations.AddField(
            model_name='device',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app01.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='onu',
            unique_together={('interface', 'olt')},
        ),
        migrations.AlterUniqueTogether(
            name='olt',
            unique_together={('interface', 'epon')},
        ),
    ]
